### ISSUE TITLE
UnboundLocalError: local variable 'amino' referenced before assignment

### ISSUE THREAD

**Issue by Schneider1707** [zeviel/AminoCoinGeneratorBo#29]
При запуске вылезает ошибка:

Traceback (most recent call last):
  File "C:\Users\green\AminoCoinGeneratorBo\main.py", line 22, in <module>
    utils.main_process()
  File "C:\Users\green\AminoCoinGeneratorBo\src\utils.py", line 111, in main_process
    ndc_id = amino.Amino().get_from_code(
UnboundLocalError: local variable 'amino' referenced before assignment

**Comment by zeviel** [comment]
жди обновление
