### ISSUE TITLE
UnboundLocalError: cannot access local variable 'amino' where it is not associated with a value

### ISSUE THREAD

**Issue by Schneider1707** [zeviel/AminoCoinGeneratorBo#31]
Вылезает такая ошибка: 
Traceback (most recent call last):
  File "C:\Users\green\AminoCoinGeneratorBo\main.py", line 22, in <module>
    utils.start_generator()
  File "C:\Users\green\AminoCoinGeneratorBo\src\utils.py", line 114, in start_generator
    ndc_id = amino.Amino().get_from_code(
             ^^^^^
UnboundLocalError: cannot access local variable 'amino' where it is not associated with a value

**Comment by zeviel** [comment]
день фиксить
